version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ocrc_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ocrc_api
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app      # monta código para live-reload
      - ./backend/alembic:/app/alembic

volumes:
  db_data:
